Chore/add intro paragraph to docs.claudie.io
berops/claudie pull request #1252
Opened 2024-03-01 07:25 UTC by JKBGIT1

closes https://github.com/berops/claudie/issues/1244

2024-03-01 12:35 UTC, bernardhalas commented on docs/index.md
> +Claudie is a platform for managing multi-cloud and hybrid-cloud Kubernetes clusters with support for nodepools across different cloud-providers and on-premise data centers.
```suggestion
Claudie is a platform for managing multi-cloud and hybrid-cloud Kubernetes clusters. These Kubernetes clusters can mix and match nodepools from various cloud providers, e.g. a single cluster can have a nodepool in AWS, another in GCP and another one on-premises. This is our opinionated way to build multi-cloud and hybrid-cloud Kubernetes infrastructure. On top of that Claudie supports Cluster Autoscaler on the managed clusters.
```

2024-03-01 12:37 UTC, bernardhalas requested changes
I've left minor comments for your assessment. Thank you @JKBGIT1

2024-03-04 08:52 UTC, JKBGIT1 commented
Hi @bernardhalas please take a look at the changes.

2024-03-18 08:04 UTC, bernardhalas approved these changes
Thanks @JKBGIT1

2024-03-18 08:04 UTC, merged