fix:trim prefix for node names
Berops/claudie pull request #475
Opened 2022-12-29 16:29 UTC by Despire

Fixes the issue where when the changeApiEndpoint playbook was run would reference the old node names with the prefix.

2022-12-29 16:45 UTC, MiroslavRepka requested changes
LGTM, please see my comments. Thanks, @Despire for spotting the issue!

2022-12-29 16:45 UTC, MiroslavRepka commented on services/ansibler/server/server.go
> +			log.Info().Msgf("LoadBalancer %s has not found a target k8s cluster %s", lb.ClusterInfo.Name, lb.TargetedK8S)
Isn't this considered an error/warning? If we have a Loadbalancer in a state which does not target any Kubernetes cluster, it should be caught by the frontend, thus if we detect it here, something went wrong.

2022-12-29 16:45 UTC, MiroslavRepka commented on services/ansibler/server/server.go
> +			log.Info().Msgf("Loadbalancer %s has not found a target k8s cluster (%s)", lb.ClusterInfo.Name, lb.TargetedK8S)
Isn't this considered an error/warning? If we have a Loadbalancer in a state which does not target any Kubernetes cluster, it should be caught by the frontend, thus if we detect it here, something went wrong.

2022-12-29 16:45 UTC, MiroslavRepka commented on services/ansibler/server/server.go
> +		clusterIDs      = make(map[string]string)         //[k8sClusterName]prefix (clusterName + hash)
Just for the consistency
`//[k8sClusterName]prefix (clusterName + hash)`  -> `//[k8sClusterName]clusterID (<clusterName>-<hash>)`

2022-12-29 16:45 UTC, MiroslavRepka commented on services/ansibler/server/server.go
> +		clusterIDs      = make(map[string]string)         //[k8sClusterName]prefix (clusterName + hash)
Just for the consistency
`//[k8sClusterName]prefix (clusterName + hash)`  -> `//[k8sClusterName]clusterID (<clusterName>-<hash>)`

2022-12-29 19:36 UTC, Despire commented
Changes implemented, also changed to `inventory_hostname` which actually will use the name from the inventory file.

2022-12-30 09:35 UTC, MiroslavRepka approved these changes

2022-12-30 09:42 UTC, merged