Feat/longhorn replicas
berops/claudie pull request #648
Opened 2023-03-20 15:28 UTC by MiroslavRepka

This PR fixes #564 by implementing the algorithm, run upon node deletion, which tries to create a new replica for the longhorn volume, if any replicas will be lost due to node deletion.

It also fixes a small bug, when deleting master nodes (case when the API endpoint was not defined).

An additional feature is the introduction of variadic functions for the `kubectl` package.

2023-03-20 15:44 UTC, MarioUhrik approved these changes
LGTM, if you've sufficiently tested that the new behavior is as you expect

2023-03-20 19:31 UTC, wULLSnpAXbWZGYDYyhWTKKspEQoaYxXyhoisqHf requested changes
had a look, looks great, had some questions/suggestions.

2023-03-20 19:31 UTC, wULLSnpAXbWZGYDYyhWTKKspEQoaYxXyhoisqHf commented on services/kuber/server/nodes/nodes.go
> +// assureReplication tries to assure, that replicas for each longhorn volume are migrated to nodes, which will remain in the
I cannot figure out the ending of this sentence..
regardless, it should probably be added.

2023-03-20 19:31 UTC, wULLSnpAXbWZGYDYyhWTKKspEQoaYxXyhoisqHf commented on services/kuber/server/nodes/nodes.go
> +				// Delete old replica, on to be deleted node.
`Delete old replica, on to be deleted node.` -> `Delete old replica on a to-be-deleted node.`

2023-03-21 07:48 UTC, wULLSnpAXbWZGYDYyhWTKKspEQoaYxXyhoisqHf commented on internal/kubectl/kubectl.go
> +	command := fmt.Sprintf("kubectl apply -f %s %s", manifest, kubeconfig)
that's right, my bad :)

2023-03-21 18:14 UTC, cloudziu approved these changes

2023-03-23 16:26 UTC, wULLSnpAXbWZGYDYyhWTKKspEQoaYxXyhoisqHf approved these changes
great stuff, LGTM, thanks @MiroslavRepka! :rocket:

2023-03-24 11:03 UTC, merged